2011/05/09 20:36:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gil".' in D:\wamp\www\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 D:\wamp\www\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('gil')
#1 D:\wamp\www\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 D:\wamp\www\ferramenta\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/ferramenta/index.php?r=gil
2011/05/09 20:38:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gil".' in D:\wamp\www\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 D:\wamp\www\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('gil')
#1 D:\wamp\www\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 D:\wamp\www\ferramenta\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/ferramenta/index.php?r=gil
2011/05/09 20:39:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gil".' in D:\wamp\www\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 D:\wamp\www\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('gil')
#1 D:\wamp\www\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 D:\wamp\www\ferramenta\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/ferramenta/index.php?r=gil
2011/05/09 20:41:16 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in D:\wamp\www\yii\framework\db\CDbConnection.php:348
Stack trace:
#0 D:\wamp\www\yii\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 D:\wamp\www\yii\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 D:\wamp\www\yii\framework\base\CModule.php(372): CDbConnection->init()
#3 D:\wamp\www\yii\framework\base\CModule.php(86): CModule->getComponent('db')
#4 D:\wamp\www\yii\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 D:\wamp\www\yii\framework\web\CFormModel.php(40): CrudCode->init()
#6 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(149): CFormModel->__construct()
#7 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(61): CCodeGenerator->prepare()
#8 D:\wamp\www\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 D:\wamp\www\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 D:\wamp\www\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 D:\wamp\www\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\wamp\www\yii\framework\web\CWebApplication.php(328): CController->run('')
#13 D:\wamp\www\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('gii/crud')
#14 D:\wamp\www\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#15 D:\wamp\www\ferramenta\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/ferramenta/index.php?r=gii/crud
2011/05/09 20:41:39 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in D:\wamp\www\yii\framework\db\CDbConnection.php:348
Stack trace:
#0 D:\wamp\www\yii\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 D:\wamp\www\yii\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 D:\wamp\www\yii\framework\base\CModule.php(372): CDbConnection->init()
#3 D:\wamp\www\yii\framework\base\CModule.php(86): CModule->getComponent('db')
#4 D:\wamp\www\yii\framework\gii\generators\model\ModelCode.php(52): CModule->__get('db')
#5 D:\wamp\www\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(149): CFormModel->__construct()
#7 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(61): CCodeGenerator->prepare()
#8 D:\wamp\www\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 D:\wamp\www\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 D:\wamp\www\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 D:\wamp\www\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\wamp\www\yii\framework\web\CWebApplication.php(328): CController->run('')
#13 D:\wamp\www\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('gii/model')
#14 D:\wamp\www\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#15 D:\wamp\www\ferramenta\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/ferramenta/index.php?r=gii/model
2011/05/09 20:42:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gil".' in D:\wamp\www\yii\framework\web\CWebApplication.php:332
Stack trace:
#0 D:\wamp\www\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('gil')
#1 D:\wamp\www\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#2 D:\wamp\www\ferramenta\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/ferramenta/index.php?r=gil
2011/05/09 20:42:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: invalid data source name' in D:\wamp\www\yii\framework\db\CDbConnection.php:348
Stack trace:
#0 D:\wamp\www\yii\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 D:\wamp\www\yii\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 D:\wamp\www\yii\framework\base\CModule.php(372): CDbConnection->init()
#3 D:\wamp\www\yii\framework\base\CModule.php(86): CModule->getComponent('db')
#4 D:\wamp\www\yii\framework\gii\generators\model\ModelCode.php(52): CModule->__get('db')
#5 D:\wamp\www\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(149): CFormModel->__construct()
#7 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(61): CCodeGenerator->prepare()
#8 D:\wamp\www\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 D:\wamp\www\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 D:\wamp\www\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 D:\wamp\www\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\wamp\www\yii\framework\web\CWebApplication.php(328): CController->run('')
#13 D:\wamp\www\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('gii/model')
#14 D:\wamp\www\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#15 D:\wamp\www\ferramenta\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/ferramenta/index.php?r=gii/model
2011/05/09 20:48:01 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000]: pdo_oci_handle_factory: ORA-12514: TNS:listener não tem conhecimento sobre o serviço solicitado atualmente no descritor de conexão
 (ext\pdo_oci\oci_driver.c:579)' in D:\wamp\www\yii\framework\db\CDbConnection.php:348
Stack trace:
#0 D:\wamp\www\yii\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 D:\wamp\www\yii\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 D:\wamp\www\yii\framework\base\CModule.php(372): CDbConnection->init()
#3 D:\wamp\www\yii\framework\base\CModule.php(86): CModule->getComponent('db')
#4 D:\wamp\www\yii\framework\gii\generators\model\ModelCode.php(52): CModule->__get('db')
#5 D:\wamp\www\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(149): CFormModel->__construct()
#7 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(61): CCodeGenerator->prepare()
#8 D:\wamp\www\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 D:\wamp\www\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 D:\wamp\www\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 D:\wamp\www\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\wamp\www\yii\framework\web\CWebApplication.php(328): CController->run('')
#13 D:\wamp\www\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('gii/model')
#14 D:\wamp\www\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#15 D:\wamp\www\ferramenta\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/ferramenta/index.php?r=gii/model
2011/05/09 20:48:24 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000]: pdo_oci_handle_factory: ORA-12514: TNS:listener não tem conhecimento sobre o serviço solicitado atualmente no descritor de conexão
 (ext\pdo_oci\oci_driver.c:579)' in D:\wamp\www\yii\framework\db\CDbConnection.php:348
Stack trace:
#0 D:\wamp\www\yii\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 D:\wamp\www\yii\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 D:\wamp\www\yii\framework\base\CModule.php(372): CDbConnection->init()
#3 D:\wamp\www\yii\framework\base\CModule.php(86): CModule->getComponent('db')
#4 D:\wamp\www\yii\framework\gii\generators\model\ModelCode.php(52): CModule->__get('db')
#5 D:\wamp\www\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(149): CFormModel->__construct()
#7 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(61): CCodeGenerator->prepare()
#8 D:\wamp\www\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 D:\wamp\www\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 D:\wamp\www\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 D:\wamp\www\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\wamp\www\yii\framework\web\CWebApplication.php(328): CController->run('')
#13 D:\wamp\www\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('gii/model')
#14 D:\wamp\www\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#15 D:\wamp\www\ferramenta\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/ferramenta/index.php?r=gii/model
2011/05/09 20:50:13 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000]: pdo_oci_handle_factory: ORA-12514: TNS:listener não tem conhecimento sobre o serviço solicitado atualmente no descritor de conexão
 (ext\pdo_oci\oci_driver.c:579)' in D:\wamp\www\yii\framework\db\CDbConnection.php:348
Stack trace:
#0 D:\wamp\www\yii\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 D:\wamp\www\yii\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 D:\wamp\www\yii\framework\base\CModule.php(372): CDbConnection->init()
#3 D:\wamp\www\yii\framework\base\CModule.php(86): CModule->getComponent('db')
#4 D:\wamp\www\yii\framework\gii\generators\model\ModelCode.php(52): CModule->__get('db')
#5 D:\wamp\www\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(149): CFormModel->__construct()
#7 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(61): CCodeGenerator->prepare()
#8 D:\wamp\www\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 D:\wamp\www\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 D:\wamp\www\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 D:\wamp\www\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\wamp\www\yii\framework\web\CWebApplication.php(328): CController->run('')
#13 D:\wamp\www\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('gii/model')
#14 D:\wamp\www\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#15 D:\wamp\www\ferramenta\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/ferramenta/index.php?r=gii/model
2011/05/09 20:50:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000]: pdo_oci_handle_factory: ORA-12514: TNS:listener não tem conhecimento sobre o serviço solicitado atualmente no descritor de conexão
 (ext\pdo_oci\oci_driver.c:579)' in D:\wamp\www\yii\framework\db\CDbConnection.php:348
Stack trace:
#0 D:\wamp\www\yii\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 D:\wamp\www\yii\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 D:\wamp\www\yii\framework\base\CModule.php(372): CDbConnection->init()
#3 D:\wamp\www\yii\framework\base\CModule.php(86): CModule->getComponent('db')
#4 D:\wamp\www\yii\framework\gii\generators\model\ModelCode.php(52): CModule->__get('db')
#5 D:\wamp\www\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(149): CFormModel->__construct()
#7 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(61): CCodeGenerator->prepare()
#8 D:\wamp\www\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 D:\wamp\www\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 D:\wamp\www\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 D:\wamp\www\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\wamp\www\yii\framework\web\CWebApplication.php(328): CController->run('')
#13 D:\wamp\www\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('gii/model')
#14 D:\wamp\www\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#15 D:\wamp\www\ferramenta\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/ferramenta/index.php?r=gii/model
2011/05/09 20:52:32 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000]: pdo_oci_handle_factory: ORA-12537: TNS:conexão fechada
 (ext\pdo_oci\oci_driver.c:579)' in D:\wamp\www\yii\framework\db\CDbConnection.php:348
Stack trace:
#0 D:\wamp\www\yii\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 D:\wamp\www\yii\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 D:\wamp\www\yii\framework\base\CModule.php(372): CDbConnection->init()
#3 D:\wamp\www\yii\framework\base\CModule.php(86): CModule->getComponent('db')
#4 D:\wamp\www\yii\framework\gii\generators\model\ModelCode.php(52): CModule->__get('db')
#5 D:\wamp\www\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(149): CFormModel->__construct()
#7 D:\wamp\www\yii\framework\gii\CCodeGenerator.php(61): CCodeGenerator->prepare()
#8 D:\wamp\www\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 D:\wamp\www\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 D:\wamp\www\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 D:\wamp\www\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\wamp\www\yii\framework\web\CWebApplication.php(328): CController->run('')
#13 D:\wamp\www\yii\framework\web\CWebApplication.php(121): CWebApplication->runController('gii/model')
#14 D:\wamp\www\yii\framework\base\CApplication.php(155): CWebApplication->processRequest()
#15 D:\wamp\www\ferramenta\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/ferramenta/index.php?r=gii/model
